package org.safehaus.stash;


public class TestUtil
{
    public static final String STASH_URL = "http://test-stash.critical-factor.com";
    public static final String PROJECT_KEY = "SSH";
    public static final String STASH_REPOS_JSON =
            "{\n" + "\"size\": 1,\n" + "\"limit\": 25,\n" + "\"isLastPage\": true,\n" + "\"values\": [\n" + "{\n" +
                    "\"slug\": \"hub\",\n" + "\"id\": 3,\n" + "\"name\": \"hub\",\n" + "\"scmId\": \"git\",\n"
                    + "\"state\": \"AVAILABLE\",\n" + "\"statusMessage\": \"Available\",\n" + "\"forkable\": true,\n"
                    + "\"project\": {\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n" + "\"url\": \"/projects"
                    + "/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n" + "}\n" + "]\n" + "}\n"
                    + "},\n" + "\"public\": false,\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/browse\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"cloneUrl\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"links\": {\n" + "\"clone\": [\n" + "{\n"
                    + "\"href\": \"ssh://git@test-stash.critical-factor.com:7999/ssh/hub.git\",\n"
                    + "\"name\": \"ssh\"\n" + "},\n" + "{\n" + "\"href\": \"http://daliev@test-stash.critical-factor"
                    + ".com/scm/ssh/hub.git\",\n" + "\"name\": \"http\"\n" + "}\n" + "],\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/browse\"\n" + "}\n"
                    + "]\n" + "}\n" + "}\n" + "],\n" + "\"start\": 0\n" + "}";
    public static final String REPO_SLUG = "hub";
    public static final String STASH_REPO_JSON =
            "{\n" + "\"slug\": \"hub\",\n" + "\"id\": 3,\n" + "\"name\": \"hub\",\n" + "\"scmId\": \"git\",\n" +
                    "\"state\": \"AVAILABLE\",\n" + "\"statusMessage\": \"Available\",\n" + "\"forkable\": true,\n"
                    + "\"project\": {\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n" + "\"url\": \"/projects"
                    + "/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n" + "}\n" + "]\n" + "}\n"
                    + "},\n" + "\"public\": false,\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/browse\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"cloneUrl\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"links\": {\n" + "\"clone\": [\n" + "{\n"
                    + "\"href\": \"ssh://git@test-stash.critical-factor.com:7999/ssh/hub.git\",\n"
                    + "\"name\": \"ssh\"\n" + "},\n" + "{\n" + "\"href\": \"http://daliev@test-stash.critical-factor"
                    + ".com/scm/ssh/hub.git\",\n" + "\"name\": \"http\"\n" + "}\n" + "],\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/browse\"\n" + "}\n"
                    + "]\n" + "}\n" + "}";
    public static final String MASTER_BRANCH = "master";
    public static final String STASH_PROJECT_JSON =
            "{\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n" + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n"
                    + "}\n" + "]\n" + "}\n" + "}";
    public static final String STASH_PROJECTS_JSON =
            "{\n" + "\"size\": 4,\n" + "\"limit\": 25,\n" + "\"isLastPage\": true,\n" + "\"values\": [\n" + "{\n"
                    + "\"key\": \"AUTO\",\n" + "\"id\": 62,\n" + "\"name\": \"Automation System\",\n"
                    + "\"description\": \"This is the Tulpar and Subutai Automation System\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/AUTO\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/AUTO\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "{\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "{\n" + "\"key\": \"TULPAR\",\n" + "\"id\": 41,\n"
                    + "\"name\": \"Tulpar\",\n" + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/TULPAR\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/TULPAR\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "{\n" + "\"key\": \"WAN\",\n" + "\"id\": 66,\n"
                    + "\"name\": \"WANtastic\",\n" + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n"
                    + "\"link\": {\n" + "\"url\": \"/projects/WAN\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"links\": {\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/WAN\"\n" + "}\n" + "]\n" + "}\n"
                    + "}\n" + "],\n" + "\"start\": 0\n" + "}";

    public static final String STASH_GROUP_JSON =
            "{\n" + "\"size\": 2,\n" + "\"limit\": 25,\n" + "\"isLastPage\": true,\n" + "\"values\": [\n" + "{\n"
                    + "\"group\": {\n" + "\"name\": \"hub-admins\"\n" + "},\n" + "\"permission\": \"PROJECT_ADMIN\"\n"
                    + "},\n" + "{\n" + "\"group\": {\n" + "\"name\": \"hub-team\"\n" + "},\n"
                    + "\"permission\": \"PROJECT_WRITE\"\n" + "}\n" + "],\n" + "\"start\": 0\n" + "}";

    public static final String STASH_PULL_REQUESTS_JSON =
            "{\n" + "\"size\": 1,\n" + "\"limit\": 1,\n" + "\"isLastPage\": false,\n" + "\"values\": [\n" + "{\n"
                    + "\"id\": 67,\n" + "\"version\": 1,\n" + "\"title\": \"Hub120 monitoring\",\n"
                    + "\"description\": \"* PeerOffline with server monitoring\\ \\ * merge prepare\\ \\ * layout "
                    + "fix\",\n" + "\"state\": \"MERGED\",\n" + "\"open\": false,\n" + "\"closed\": true,\n"
                    + "\"createdDate\": 1412838554877,\n" + "\"updatedDate\": 1412840161269,\n" + "\"fromRef\": {\n"
                    + "\"id\": \"refs/heads/hub120-monitoring\",\n" + "\"displayId\": \"hub120-monitoring\",\n"
                    + "\"latestChangeset\": \"2fda08f8ba14974154d32f90c5487df04ff10faf\",\n" + "\"repository\": {\n"
                    + "\"slug\": \"hub\",\n" + "\"id\": 3,\n" + "\"name\": \"hub\",\n" + "\"scmId\": \"git\",\n"
                    + "\"state\": \"AVAILABLE\",\n" + "\"statusMessage\": \"Available\",\n" + "\"forkable\": true,\n"
                    + "\"project\": {\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "\"public\": false,\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/browse\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"cloneUrl\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"links\": {\n" + "\"clone\": [\n" + "{\n"
                    + "\"href\": \"ssh://git@test-stash.critical-factor.com:7999/ssh/hub.git\",\n"
                    + "\"name\": \"ssh\"\n" + "},\n" + "{\n"
                    + "\"href\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"name\": \"http\"\n" + "}\n" + "],\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/browse\"\n" + "}\n"
                    + "]\n" + "}\n" + "}\n" + "},\n" + "\"toRef\": {\n" + "\"id\": \"refs/heads/master\",\n"
                    + "\"displayId\": \"master\",\n"
                    + "\"latestChangeset\": \"130ddb66340d9ffa4e8356910e3abacf8dde9579\",\n" + "\"repository\": {\n"
                    + "\"slug\": \"hub\",\n" + "\"id\": 3,\n" + "\"name\": \"hub\",\n" + "\"scmId\": \"git\",\n"
                    + "\"state\": \"AVAILABLE\",\n" + "\"statusMessage\": \"Available\",\n" + "\"forkable\": true,\n"
                    + "\"project\": {\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "\"public\": false,\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/browse\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"cloneUrl\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"links\": {\n" + "\"clone\": [\n" + "{\n"
                    + "\"href\": \"ssh://git@test-stash.critical-factor.com:7999/ssh/hub.git\",\n"
                    + "\"name\": \"ssh\"\n" + "},\n" + "{\n"
                    + "\"href\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"name\": \"http\"\n" + "}\n" + "],\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/browse\"\n" + "}\n"
                    + "]\n" + "}\n" + "}\n" + "},\n" + "\"author\": {\n" + "\"user\": {\n"
                    + "\"name\": \"ekuttubaev\",\n" + "\"id\": 56,\n" + "\"displayName\": \"ekuttubaev\",\n"
                    + "\"active\": false,\n" + "\"slug\": \"ekuttubaev\",\n" + "\"type\": \"NORMAL\",\n"
                    + "\"link\": {\n" + "\"url\": \"/users/ekuttubaev\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"links\": {\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/users/ekuttubaev\"\n" + "}\n" + "]\n" + "}\n"
                    + "},\n" + "\"role\": \"AUTHOR\",\n" + "\"approved\": false\n" + "},\n" + "\"reviewers\": [\n"
                    + "{\n" + "\"user\": {\n" + "\"name\": \"abeishenaliev\",\n"
                    + "\"emailAddress\": \"abeishenaliev@critical-factor.com\",\n" + "\"id\": 6,\n"
                    + "\"displayName\": \"Azilet Beishenaliev\",\n" + "\"active\": false,\n"
                    + "\"slug\": \"abeishenaliev\",\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/users/abeishenaliev\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/users/abeishenaliev\"\n" + "}\n" + "]\n"
                    + "}\n" + "},\n" + "\"role\": \"REVIEWER\",\n" + "\"approved\": false\n" + "},\n" + "{\n"
                    + "\"user\": {\n" + "\"name\": \"aasanaliev\",\n"
                    + "\"emailAddress\": \"aasanaliev@critical-factor.com\",\n" + "\"id\": 10,\n"
                    + "\"displayName\": \"Askhat Asanaliev\",\n" + "\"active\": false,\n"
                    + "\"slug\": \"aasanaliev\",\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/users/aasanaliev\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/users/aasanaliev\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "\"role\": \"REVIEWER\",\n" + "\"approved\": true\n" + "}\n"
                    + "],\n" + "\"participants\": [ ],\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/pull-requests/67\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"links\": {\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/pull-requests/67\"\n"
                    + "}\n" + "]\n" + "}\n" + "}\n" + "],\n" + "\"start\": 0,\n" + "\"nextPageStart\": 1\n" + "}";

    public static final String STASH_PULL_REQUEST_JSON =
            "{\n" + "\"id\": 1,\n" + "\"version\": 1,\n" + "\"title\": \"HUB-31\",\n"
                    + "\"description\": \"* Git testing\\ \\ * Deleted test contoller\",\n" + "\"state\": \"MERGED\",\n"
                    + "\"open\": false,\n" + "\"closed\": true,\n" + "\"createdDate\": 1410507192695,\n"
                    + "\"updatedDate\": 1410507333928,\n" + "\"fromRef\": {\n" + "\"id\": \"refs/heads/HUB-31\",\n"
                    + "\"displayId\": \"HUB-31\",\n"
                    + "\"latestChangeset\": \"33537628e7d9bda85897d7861ccc4a56a8b37aa2\",\n" + "\"repository\": {\n"
                    + "\"slug\": \"hub\",\n" + "\"id\": 3,\n" + "\"name\": \"hub\",\n" + "\"scmId\": \"git\",\n"
                    + "\"state\": \"AVAILABLE\",\n" + "\"statusMessage\": \"Available\",\n" + "\"forkable\": true,\n"
                    + "\"project\": {\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "\"public\": false,\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/browse\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"cloneUrl\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"links\": {\n" + "\"clone\": [\n" + "{\n"
                    + "\"href\": \"ssh://git@test-stash.critical-factor.com:7999/ssh/hub.git\",\n"
                    + "\"name\": \"ssh\"\n" + "},\n" + "{\n"
                    + "\"href\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"name\": \"http\"\n" + "}\n" + "],\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/browse\"\n" + "}\n"
                    + "]\n" + "}\n" + "}\n" + "},\n" + "\"toRef\": {\n" + "\"id\": \"refs/heads/master\",\n"
                    + "\"displayId\": \"master\",\n"
                    + "\"latestChangeset\": \"b796f7bf69a2ac66a339dba73f9a19d3b586cd53\",\n" + "\"repository\": {\n"
                    + "\"slug\": \"hub\",\n" + "\"id\": 3,\n" + "\"name\": \"hub\",\n" + "\"scmId\": \"git\",\n"
                    + "\"state\": \"AVAILABLE\",\n" + "\"statusMessage\": \"Available\",\n" + "\"forkable\": true,\n"
                    + "\"project\": {\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "\"public\": false,\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/browse\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"cloneUrl\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"links\": {\n" + "\"clone\": [\n" + "{\n"
                    + "\"href\": \"ssh://git@test-stash.critical-factor.com:7999/ssh/hub.git\",\n"
                    + "\"name\": \"ssh\"\n" + "},\n" + "{\n"
                    + "\"href\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"name\": \"http\"\n" + "}\n" + "],\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/browse\"\n" + "}\n"
                    + "]\n" + "}\n" + "}\n" + "},\n" + "\"author\": {\n" + "\"user\": {\n"
                    + "\"name\": \"aasanaliev\",\n" + "\"emailAddress\": \"aasanaliev@critical-factor.com\",\n"
                    + "\"id\": 10,\n" + "\"displayName\": \"Askhat Asanaliev\",\n" + "\"active\": false,\n"
                    + "\"slug\": \"aasanaliev\",\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/users/aasanaliev\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/users/aasanaliev\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "\"role\": \"AUTHOR\",\n" + "\"approved\": false\n" + "},\n"
                    + "\"reviewers\": [\n" + "{\n" + "\"user\": {\n" + "\"name\": \"sakhmataliev\",\n"
                    + "\"emailAddress\": \"sakhmataliev@critical-factor.com\",\n" + "\"id\": 54,\n"
                    + "\"displayName\": \"Sydyk Akhmataliev\",\n" + "\"active\": true,\n"
                    + "\"slug\": \"sakhmataliev\",\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/users/sakhmataliev\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/users/sakhmataliev\"\n" + "}\n" + "]\n" + "}\n"
                    + "},\n" + "\"role\": \"REVIEWER\",\n" + "\"approved\": false\n" + "}\n" + "],\n"
                    + "\"participants\": [ ],\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/pull-requests/1\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"links\": {\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/pull-requests/1\"\n"
                    + "}\n" + "]\n" + "}\n" + "}";

    public static final String STASH_PULL_REQUEST_ACTIVITY_JSON =
            "{\n" + "    \"size\": 3,\n" + "    \"limit\": 25,\n" + "    \"isLastPage\": true,\n"
                    + "    \"values\": [\n" + "        {\n" + "            \"id\": 101,\n"
                    + "            \"createdDate\": 1359065920,\n" + "            \"user\": {\n"
                    + "                \"name\": \"jcitizen\",\n"
                    + "                \"emailAddress\": \"jane@example.com\",\n" + "                \"id\": 101,\n"
                    + "                \"displayName\": \"Jane Citizen\",\n" + "                \"active\": true,\n"
                    + "                \"slug\": \"jcitizen\",\n" + "                \"type\": \"NORMAL\"\n"
                    + "            },\n" + "            \"action\": \"COMMENTED\",\n"
                    + "            \"commentAction\": \"ADDED\",\n" + "            \"comment\": {\n"
                    + "                \"properties\": {\n" + "                    \"key\": \"value\"\n"
                    + "                },\n" + "                \"id\": 1,\n" + "                \"version\": 1,\n"
                    + "                \"text\": \"A measured reply.\",\n" + "                \"author\": {\n"
                    + "                    \"name\": \"jcitizen\",\n"
                    + "                    \"emailAddress\": \"jane@example.com\",\n"
                    + "                    \"id\": 101,\n" + "                    \"displayName\": \"Jane Citizen\",\n"
                    + "                    \"active\": true,\n" + "                    \"slug\": \"jcitizen\",\n"
                    + "                    \"type\": \"NORMAL\"\n" + "                },\n"
                    + "                \"createdDate\": 1433803137990,\n"
                    + "                \"updatedDate\": 1433803137990,\n" + "                \"comments\": [\n"
                    + "                    {\n" + "                        \"properties\": {\n"
                    + "                            \"key\": \"value\"\n" + "                        },\n"
                    + "                        \"id\": 1,\n" + "                        \"version\": 1,\n"
                    + "                        \"text\": \"An insightful comment.\",\n"
                    + "                        \"author\": {\n"
                    + "                            \"name\": \"jcitizen\",\n"
                    + "                            \"emailAddress\": \"jane@example.com\",\n"
                    + "                            \"id\": 101,\n"
                    + "                            \"displayName\": \"Jane Citizen\",\n"
                    + "                            \"active\": true,\n"
                    + "                            \"slug\": \"jcitizen\",\n"
                    + "                            \"type\": \"NORMAL\"\n" + "                        },\n"
                    + "                        \"createdDate\": 1433803137977,\n"
                    + "                        \"updatedDate\": 1433803137977,\n"
                    + "                        \"comments\": [],\n" + "                        \"attributes\": {\n"
                    + "                            \"key\": [\n" + "                                \"value\"\n"
                    + "                            ]\n" + "                        },\n"
                    + "                        \"tasks\": [],\n"
                    + "                        \"permittedOperations\": {\n"
                    + "                            \"editable\": true,\n"
                    + "                            \"deletable\": true\n" + "                        }\n"
                    + "                    }\n" + "                ],\n" + "                \"attributes\": {\n"
                    + "                    \"key\": [\n" + "                        \"value\"\n"
                    + "                    ]\n" + "                },\n" + "                \"tasks\": [],\n"
                    + "                \"permittedOperations\": {\n" + "                    \"editable\": true,\n"
                    + "                    \"deletable\": true\n" + "                }\n" + "            },\n"
                    + "            \"commentAnchor\": {\n"
                    + "                \"fromHash\": \"8d51122def5632836d1cb1026e879069e10a1e13\",\n"
                    + "                \"toHash\": \"4b12658b6cd2bae179759c21537b4ec6627ff83b\",\n"
                    + "                \"line\": 1,\n" + "                \"lineType\": \"CONTEXT\",\n"
                    + "                \"fileType\": \"FROM\",\n" + "                \"path\": \"path/to/file\",\n"
                    + "                \"srcPath\": \"path/to/file\",\n" + "                \"orphaned\": false\n"
                    + "            }\n" + "        },\n" + "        {\n" + "            \"id\": 101,\n"
                    + "            \"createdDate\": 1359065920,\n" + "            \"user\": {\n"
                    + "                \"name\": \"jcitizen\",\n"
                    + "                \"emailAddress\": \"jane@example.com\",\n" + "                \"id\": 101,\n"
                    + "                \"displayName\": \"Jane Citizen\",\n" + "                \"active\": true,\n"
                    + "                \"slug\": \"jcitizen\",\n" + "                \"type\": \"NORMAL\"\n"
                    + "            },\n" + "            \"action\": \"RESCOPED\",\n"
                    + "            \"fromHash\": \"abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde\",\n"
                    + "            \"previousFromHash\": \"bcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdea\",\n"
                    + "            \"previousToHash\": \"cdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeab\",\n"
                    + "            \"toHash\": \"ddeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabc\",\n"
                    + "            \"added\": {\n" + "                \"changesets\": [\n" + "                    {\n"
                    + "                        \"id\": \"abcdef0123abcdef4567abcdef8987abcdef6543\",\n"
                    + "                        \"displayId\": \"abcdef0123a\",\n"
                    + "                        \"author\": {\n" + "                            \"name\": \"charlie\",\n"
                    + "                            \"emailAddress\": \"charlie@example.com\"\n"
                    + "                        },\n" + "                        \"authorTimestamp\": 1433803140570,\n"
                    + "                        \"message\": \"WIP on feature 1\",\n"
                    + "                        \"parents\": [\n" + "                            {\n"
                    + "                                \"id\": \"abcdef0123abcdef4567abcdef8987abcdef6543\",\n"
                    + "                                \"displayId\": \"abcdef0\"\n" + "                            }\n"
                    + "                        ]\n" + "                    }\n" + "                ],\n"
                    + "                \"commits\": [\n" + "                    {\n"
                    + "                        \"id\": \"abcdef0123abcdef4567abcdef8987abcdef6543\",\n"
                    + "                        \"displayId\": \"abcdef0123a\",\n"
                    + "                        \"author\": {\n" + "                            \"name\": \"charlie\",\n"
                    + "                            \"emailAddress\": \"charlie@example.com\"\n"
                    + "                        },\n" + "                        \"authorTimestamp\": 1433803137863,\n"
                    + "                        \"message\": \"WIP on feature 1\",\n"
                    + "                        \"parents\": [\n" + "                            {\n"
                    + "                                \"id\": \"abcdef0123abcdef4567abcdef8987abcdef6543\",\n"
                    + "                                \"displayId\": \"abcdef0\"\n" + "                            }\n"
                    + "                        ]\n" + "                    }\n" + "                ],\n"
                    + "                \"total\": 1\n" + "            },\n" + "            \"removed\": {\n"
                    + "                \"changesets\": [\n" + "                    {\n"
                    + "                        \"id\": \"def0123abcdef4567abcdef8987abcdef6543abc\",\n"
                    + "                        \"displayId\": \"def0123abcd\",\n"
                    + "                        \"author\": {\n" + "                            \"name\": \"charlie\",\n"
                    + "                            \"emailAddress\": \"charlie@example.com\"\n"
                    + "                        },\n" + "                        \"authorTimestamp\": 1433803140570,\n"
                    + "                        \"message\": \"More work on feature 1\",\n"
                    + "                        \"parents\": [\n" + "                            {\n"
                    + "                                \"id\": \"abcdef0123abcdef4567abcdef8987abcdef6543\",\n"
                    + "                                \"displayId\": \"abcdef0\"\n" + "                            }\n"
                    + "                        ]\n" + "                    }\n" + "                ],\n"
                    + "                \"commits\": [\n" + "                    {\n"
                    + "                        \"id\": \"def0123abcdef4567abcdef8987abcdef6543abc\",\n"
                    + "                        \"displayId\": \"def0123abcd\",\n"
                    + "                        \"author\": {\n" + "                            \"name\": \"charlie\",\n"
                    + "                            \"emailAddress\": \"charlie@example.com\"\n"
                    + "                        },\n" + "                        \"authorTimestamp\": 1433803137864,\n"
                    + "                        \"message\": \"More work on feature 1\",\n"
                    + "                        \"parents\": [\n" + "                            {\n"
                    + "                                \"id\": \"abcdef0123abcdef4567abcdef8987abcdef6543\",\n"
                    + "                                \"displayId\": \"abcdef0\"\n" + "                            }\n"
                    + "                        ]\n" + "                    }\n" + "                ],\n"
                    + "                \"total\": 1\n" + "            }\n" + "        },\n" + "        {\n"
                    + "            \"id\": 101,\n" + "            \"createdDate\": 1359085920,\n"
                    + "            \"user\": {\n" + "                \"name\": \"jcitizen\",\n"
                    + "                \"emailAddress\": \"jane@example.com\",\n" + "                \"id\": 101,\n"
                    + "                \"displayName\": \"Jane Citizen\",\n" + "                \"active\": true,\n"
                    + "                \"slug\": \"jcitizen\",\n" + "                \"type\": \"NORMAL\"\n"
                    + "            },\n" + "            \"action\": \"MERGED\"\n" + "        }\n" + "    ],\n"
                    + "    \"start\": 0\n" + "}";

    public static final String STASH_PULL_REQUEST_COMMITS_JSON =
            "{\n" + "\"values\": [\n" + "{\n" + "\"id\": \"33537628e7d9bda85897d7861ccc4a56a8b37aa2\",\n"
                    + "\"displayId\": \"3353762\",\n" + "\"author\": {\n" + "\"name\": \"Askat Asanaliev\",\n"
                    + "\"emailAddress\": \"aasanaliev@safehaus.org\"\n" + "},\n"
                    + "\"authorTimestamp\": 1410507145000,\n" + "\"message\": \"Deleted test contoller\",\n"
                    + "\"parents\": [\n" + "{\n" + "\"id\": \"683ade1713133226a66180592bb87183b618abab\",\n"
                    + "\"displayId\": \"683ade1\"\n" + "}\n" + "]\n" + "},\n" + "{\n"
                    + "\"id\": \"683ade1713133226a66180592bb87183b618abab\",\n" + "\"displayId\": \"683ade1\",\n"
                    + "\"author\": {\n" + "\"name\": \"Askat Asanaliev\",\n"
                    + "\"emailAddress\": \"aasanaliev@safehaus.org\"\n" + "},\n"
                    + "\"authorTimestamp\": 1410506983000,\n" + "\"message\": \"Git testing\",\n" + "\"parents\": [\n"
                    + "{\n" + "\"id\": \"b796f7bf69a2ac66a339dba73f9a19d3b586cd53\",\n" + "\"displayId\": \"b796f7b\"\n"
                    + "}\n" + "]\n" + "}\n" + "],\n" + "\"size\": 2,\n" + "\"isLastPage\": true,\n" + "\"start\": 0,\n"
                    + "\"limit\": 10,\n" + "\"nextPageStart\": null\n" + "}";

    public static final String STASH_BRANCHES_JSON =
            "{\n" + "    \"size\": 1,\n" + "    \"limit\": 25,\n" + "    \"isLastPage\": true,\n"
                    + "    \"values\": [\n" + "        {\n" + "            \"id\": \"refs/heads/master\",\n"
                    + "            \"displayId\": \"master\",\n"
                    + "            \"latestChangeset\": \"8d51122def5632836d1cb1026e879069e10a1e13\",\n"
                    + "            \"latestCommit\": \"8d51122def5632836d1cb1026e879069e10a1e13\",\n"
                    + "            \"isDefault\": true\n" + "        }\n" + "    ],\n" + "    \"start\": 0\n" + "}";

    public static final String STASH_BRANCH_JSON =
            "{\n" + "    \"id\": \"refs/heads/master\",\n" + "    \"displayId\": \"master\",\n"
                    + "    \"latestChangeset\": \"8d51122def5632836d1cb1026e879069e10a1e13\",\n"
                    + "    \"latestCommit\": \"8d51122def5632836d1cb1026e879069e10a1e13\",\n"
                    + "    \"isDefault\": true\n" + "}";

    public static final String STASH_PULL_REQUEST_CHANGES_JSON =
            "{\n" + "    \"size\": 1,\n" + "    \"limit\": 25,\n" + "    \"isLastPage\": true,\n"
                    + "    \"values\": [\n" + "        {\n"
                    + "            \"contentId\": \"abcdef0123abcdef4567abcdef8987abcdef6543\",\n"
                    + "            \"fromContentId\": \"bcdef0123abcdef4567abcdef8987abcdef6543a\",\n"
                    + "            \"path\": {\n" + "                \"components\": [\n"
                    + "                    \"new\",\n" + "                    \"path\",\n"
                    + "                    \"to\",\n" + "                    \"file.txt\"\n" + "                ],\n"
                    + "                \"parent\": \"new/path/to\",\n" + "                \"name\": \"file.txt\",\n"
                    + "                \"extension\": \"txt\",\n"
                    + "                \"toString\": \"new/path/to/file.txt\"\n" + "            },\n"
                    + "            \"executable\": false,\n" + "            \"percentUnchanged\": 98,\n"
                    + "            \"type\": \"MOVE\",\n" + "            \"nodeType\": \"FILE\",\n"
                    + "            \"srcPath\": {\n" + "                \"components\": [\n"
                    + "                    \"path\",\n" + "                    \"to\",\n"
                    + "                    \"file.txt\"\n" + "                ],\n"
                    + "                \"parent\": \"path/to\",\n" + "                \"name\": \"file.txt\",\n"
                    + "                \"extension\": \"txt\",\n"
                    + "                \"toString\": \"path/to/file.txt\"\n" + "            },\n"
                    + "            \"srcExecutable\": false,\n" + "            \"link\": {\n"
                    + "                \"url\": \"http://link/to/restchange\",\n"
                    + "                \"rel\": \"self\"\n" + "            },\n" + "            \"links\": {\n"
                    + "                \"self\": [\n" + "                    {\n"
                    + "                        \"href\": \"http://link/to/restchange\"\n" + "                    }\n"
                    + "                ]\n" + "            }\n" + "        }\n" + "    ],\n" + "    \"start\": 0\n"
                    + "}";

    public static final String STASH_COMMITS_JSON =
            "{\n" + "    \"size\": 1,\n" + "    \"limit\": 25,\n" + "    \"isLastPage\": true,\n"
                    + "    \"values\": [\n" + "        {\n"
                    + "            \"id\": \"def0123abcdef4567abcdef8987abcdef6543abc\",\n"
                    + "            \"displayId\": \"def0123abcd\",\n" + "            \"author\": {\n"
                    + "                \"name\": \"charlie\",\n"
                    + "                \"emailAddress\": \"charlie@example.com\"\n" + "            },\n"
                    + "            \"authorTimestamp\": 1433803137864,\n"
                    + "            \"message\": \"More work on feature 1\",\n" + "            \"parents\": [\n"
                    + "                {\n"
                    + "                    \"id\": \"abcdef0123abcdef4567abcdef8987abcdef6543\",\n"
                    + "                    \"displayId\": \"abcdef0\"\n" + "                }\n" + "            ]\n"
                    + "        }\n" + "    ],\n" + "    \"start\": 0,\n" + "    \"authorCount\": 1,\n"
                    + "    \"totalCount\": 1\n" + "}";

    public static final String STASH_COMMIT_JSON = "{\n" + "    \"id\": \"abcdef0123abcdef4567abcdef8987abcdef6543\",\n"
            + "    \"displayId\": \"abcdef0123a\",\n" + "    \"author\": {\n" + "        \"name\": \"charlie\",\n"
            + "        \"emailAddress\": \"charlie@example.com\"\n" + "    },\n"
            + "    \"authorTimestamp\": 1433803137863,\n" + "    \"message\": \"WIP on feature 1\",\n"
            + "    \"parents\": [\n" + "        {\n"
            + "            \"id\": \"abcdef0123abcdef4567abcdef8987abcdef6543\",\n"
            + "            \"displayId\": \"abcdef0\"\n" + "        }\n" + "    ]\n" + "}";

    public static final String STASH_COMMIT_CHANGES_JSON =
            "{\n" + "    \"size\": 1,\n" + "    \"limit\": 25,\n" + "    \"isLastPage\": true,\n"
                    + "    \"values\": [\n" + "        {\n"
                    + "            \"contentId\": \"abcdef0123abcdef4567abcdef8987abcdef6543\",\n"
                    + "            \"fromContentId\": \"bcdef0123abcdef4567abcdef8987abcdef6543a\",\n"
                    + "            \"path\": {\n" + "                \"components\": [\n"
                    + "                    \"new\",\n" + "                    \"path\",\n"
                    + "                    \"to\",\n" + "                    \"file.txt\"\n" + "                ],\n"
                    + "                \"parent\": \"new/path/to\",\n" + "                \"name\": \"file.txt\",\n"
                    + "                \"extension\": \"txt\",\n"
                    + "                \"toString\": \"new/path/to/file.txt\"\n" + "            },\n"
                    + "            \"executable\": false,\n" + "            \"percentUnchanged\": 98,\n"
                    + "            \"type\": \"MOVE\",\n" + "            \"nodeType\": \"FILE\",\n"
                    + "            \"srcPath\": {\n" + "                \"components\": [\n"
                    + "                    \"path\",\n" + "                    \"to\",\n"
                    + "                    \"file.txt\"\n" + "                ],\n"
                    + "                \"parent\": \"path/to\",\n" + "                \"name\": \"file.txt\",\n"
                    + "                \"extension\": \"txt\",\n"
                    + "                \"toString\": \"path/to/file.txt\"\n" + "            },\n"
                    + "            \"srcExecutable\": false,\n" + "            \"link\": {\n"
                    + "                \"url\": \"http://link/to/restchange\",\n"
                    + "                \"rel\": \"self\"\n" + "            },\n" + "            \"links\": {\n"
                    + "                \"self\": [\n" + "                    {\n"
                    + "                        \"href\": \"http://link/to/restchange\"\n" + "                    }\n"
                    + "                ]\n" + "            }\n" + "        }\n" + "    ],\n" + "    \"start\": 0\n"
                    + "}";

    public static final String STASH_EVENTS_JSON =
            "{\n" + "    \"size\": 1,\n" + "    \"limit\": 25,\n" + "    \"isLastPage\": true,\n"
                    + "    \"values\": [\n" + "        {\n" + "            \"user\": {\n"
                    + "                \"name\": \"jcitizen\",\n"
                    + "                \"emailAddress\": \"jane@example.com\",\n" + "                \"id\": 101,\n"
                    + "                \"displayName\": \"Jane Citizen\",\n" + "                \"active\": true,\n"
                    + "                \"slug\": \"jcitizen\",\n" + "                \"type\": \"NORMAL\"\n"
                    + "            },\n" + "            \"action\": \"RepositoryPush\",\n"
                    + "            \"timestamp\": 1433802955040,\n" + "            \"details\": \"Details\"\n"
                    + "        }\n" + "    ],\n" + "    \"start\": 0\n" + "}";
    public static final String STASH_BUILD_STATISTICS_JSON =
            "{\n" + "    \"successful\": 3,\n" + "    \"inProgress\": 0,\n" + "    \"failed\": 1\n" + "}";

    public static final String STASH_BUILD_STATUSES_JSON =
            "{\n" + "    \"size\": 1,\n" + "    \"limit\": 25,\n" + "    \"isLastPage\": true,\n"
                    + "    \"values\": [\n" + "        {\n" + "            \"state\": \"SUCCESSFUL\",\n"
                    + "            \"key\": \"REPO-MASTER\",\n" + "            \"name\": \"REPO-MASTER-42\",\n"
                    + "            \"url\": \"https://bamboo.example.com/browse/REPO-MASTER-42\",\n"
                    + "            \"description\": \"Changes by John Doe\",\n"
                    + "            \"dateAdded\": 1433804276157\n" + "        }\n" + "    ],\n" + "    \"start\": 0\n"
                    + "}";
}
