package org.safehaus.stash;


public class TestUtil
{
    public static final String STASH_URL = "http://test-stash.critical-factor.com";
    public static final String PROJECT_KEY = "SSH";
    public static final String STASH_REPOS_JSON =
            "{\n" + "\"size\": 1,\n" + "\"limit\": 25,\n" + "\"isLastPage\": true,\n" + "\"values\": [\n" + "{\n" +
                    "\"slug\": \"hub\",\n" + "\"id\": 3,\n" + "\"name\": \"hub\",\n" + "\"scmId\": \"git\",\n"
                    + "\"state\": \"AVAILABLE\",\n" + "\"statusMessage\": \"Available\",\n" + "\"forkable\": true,\n"
                    + "\"project\": {\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n" + "\"url\": \"/projects"
                    + "/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n" + "}\n" + "]\n" + "}\n"
                    + "},\n" + "\"public\": false,\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/browse\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"cloneUrl\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"links\": {\n" + "\"clone\": [\n" + "{\n"
                    + "\"href\": \"ssh://git@test-stash.critical-factor.com:7999/ssh/hub.git\",\n"
                    + "\"name\": \"ssh\"\n" + "},\n" + "{\n" + "\"href\": \"http://daliev@test-stash.critical-factor"
                    + ".com/scm/ssh/hub.git\",\n" + "\"name\": \"http\"\n" + "}\n" + "],\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/browse\"\n" + "}\n"
                    + "]\n" + "}\n" + "}\n" + "],\n" + "\"start\": 0\n" + "}";
    public static final String REPO_SLUG = "hub";
    public static final String STASH_REPO_JSON =
            "{\n" + "\"slug\": \"hub\",\n" + "\"id\": 3,\n" + "\"name\": \"hub\",\n" + "\"scmId\": \"git\",\n" +
                    "\"state\": \"AVAILABLE\",\n" + "\"statusMessage\": \"Available\",\n" + "\"forkable\": true,\n"
                    + "\"project\": {\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n" + "\"url\": \"/projects"
                    + "/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n" + "}\n" + "]\n" + "}\n"
                    + "},\n" + "\"public\": false,\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/browse\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"cloneUrl\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"links\": {\n" + "\"clone\": [\n" + "{\n"
                    + "\"href\": \"ssh://git@test-stash.critical-factor.com:7999/ssh/hub.git\",\n"
                    + "\"name\": \"ssh\"\n" + "},\n" + "{\n" + "\"href\": \"http://daliev@test-stash.critical-factor"
                    + ".com/scm/ssh/hub.git\",\n" + "\"name\": \"http\"\n" + "}\n" + "],\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/browse\"\n" + "}\n"
                    + "]\n" + "}\n" + "}";
    public static final String MASTER_BRANCH = "master";
    public static final String STASH_PROJECT_JSON =
            "{\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n" + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n"
                    + "}\n" + "]\n" + "}\n" + "}";
    public static final String STASH_PROJECTS_JSON =
            "{\n" + "\"size\": 4,\n" + "\"limit\": 25,\n" + "\"isLastPage\": true,\n" + "\"values\": [\n" + "{\n"
                    + "\"key\": \"AUTO\",\n" + "\"id\": 62,\n" + "\"name\": \"Automation System\",\n"
                    + "\"description\": \"This is the Tulpar and Subutai Automation System\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/AUTO\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/AUTO\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "{\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "{\n" + "\"key\": \"TULPAR\",\n" + "\"id\": 41,\n"
                    + "\"name\": \"Tulpar\",\n" + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/TULPAR\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/TULPAR\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "{\n" + "\"key\": \"WAN\",\n" + "\"id\": 66,\n"
                    + "\"name\": \"WANtastic\",\n" + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n"
                    + "\"link\": {\n" + "\"url\": \"/projects/WAN\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"links\": {\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/WAN\"\n" + "}\n" + "]\n" + "}\n"
                    + "}\n" + "],\n" + "\"start\": 0\n" + "}";

    public static final String STASH_GROUP_JSON =
            "{\n" + "\"size\": 2,\n" + "\"limit\": 25,\n" + "\"isLastPage\": true,\n" + "\"values\": [\n" + "{\n"
                    + "\"group\": {\n" + "\"name\": \"hub-admins\"\n" + "},\n" + "\"permission\": \"PROJECT_ADMIN\"\n"
                    + "},\n" + "{\n" + "\"group\": {\n" + "\"name\": \"hub-team\"\n" + "},\n"
                    + "\"permission\": \"PROJECT_WRITE\"\n" + "}\n" + "],\n" + "\"start\": 0\n" + "}";

    public static final String STASH_PULL_REQUESTS_JSON =
            "{\n" + "\"size\": 1,\n" + "\"limit\": 1,\n" + "\"isLastPage\": false,\n" + "\"values\": [\n" + "{\n"
                    + "\"id\": 67,\n" + "\"version\": 1,\n" + "\"title\": \"Hub120 monitoring\",\n"
                    + "\"description\": \"* PeerOffline with server monitoring\\ \\ * merge prepare\\ \\ * layout "
                    + "fix\",\n" + "\"state\": \"MERGED\",\n" + "\"open\": false,\n" + "\"closed\": true,\n"
                    + "\"createdDate\": 1412838554877,\n" + "\"updatedDate\": 1412840161269,\n" + "\"fromRef\": {\n"
                    + "\"id\": \"refs/heads/hub120-monitoring\",\n" + "\"displayId\": \"hub120-monitoring\",\n"
                    + "\"latestChangeset\": \"2fda08f8ba14974154d32f90c5487df04ff10faf\",\n" + "\"repository\": {\n"
                    + "\"slug\": \"hub\",\n" + "\"id\": 3,\n" + "\"name\": \"hub\",\n" + "\"scmId\": \"git\",\n"
                    + "\"state\": \"AVAILABLE\",\n" + "\"statusMessage\": \"Available\",\n" + "\"forkable\": true,\n"
                    + "\"project\": {\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "\"public\": false,\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/browse\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"cloneUrl\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"links\": {\n" + "\"clone\": [\n" + "{\n"
                    + "\"href\": \"ssh://git@test-stash.critical-factor.com:7999/ssh/hub.git\",\n"
                    + "\"name\": \"ssh\"\n" + "},\n" + "{\n"
                    + "\"href\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"name\": \"http\"\n" + "}\n" + "],\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/browse\"\n" + "}\n"
                    + "]\n" + "}\n" + "}\n" + "},\n" + "\"toRef\": {\n" + "\"id\": \"refs/heads/master\",\n"
                    + "\"displayId\": \"master\",\n"
                    + "\"latestChangeset\": \"130ddb66340d9ffa4e8356910e3abacf8dde9579\",\n" + "\"repository\": {\n"
                    + "\"slug\": \"hub\",\n" + "\"id\": 3,\n" + "\"name\": \"hub\",\n" + "\"scmId\": \"git\",\n"
                    + "\"state\": \"AVAILABLE\",\n" + "\"statusMessage\": \"Available\",\n" + "\"forkable\": true,\n"
                    + "\"project\": {\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "\"public\": false,\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/browse\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"cloneUrl\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"links\": {\n" + "\"clone\": [\n" + "{\n"
                    + "\"href\": \"ssh://git@test-stash.critical-factor.com:7999/ssh/hub.git\",\n"
                    + "\"name\": \"ssh\"\n" + "},\n" + "{\n"
                    + "\"href\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"name\": \"http\"\n" + "}\n" + "],\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/browse\"\n" + "}\n"
                    + "]\n" + "}\n" + "}\n" + "},\n" + "\"author\": {\n" + "\"user\": {\n"
                    + "\"name\": \"ekuttubaev\",\n" + "\"id\": 56,\n" + "\"displayName\": \"ekuttubaev\",\n"
                    + "\"active\": false,\n" + "\"slug\": \"ekuttubaev\",\n" + "\"type\": \"NORMAL\",\n"
                    + "\"link\": {\n" + "\"url\": \"/users/ekuttubaev\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"links\": {\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/users/ekuttubaev\"\n" + "}\n" + "]\n" + "}\n"
                    + "},\n" + "\"role\": \"AUTHOR\",\n" + "\"approved\": false\n" + "},\n" + "\"reviewers\": [\n"
                    + "{\n" + "\"user\": {\n" + "\"name\": \"abeishenaliev\",\n"
                    + "\"emailAddress\": \"abeishenaliev@critical-factor.com\",\n" + "\"id\": 6,\n"
                    + "\"displayName\": \"Azilet Beishenaliev\",\n" + "\"active\": false,\n"
                    + "\"slug\": \"abeishenaliev\",\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/users/abeishenaliev\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/users/abeishenaliev\"\n" + "}\n" + "]\n"
                    + "}\n" + "},\n" + "\"role\": \"REVIEWER\",\n" + "\"approved\": false\n" + "},\n" + "{\n"
                    + "\"user\": {\n" + "\"name\": \"aasanaliev\",\n"
                    + "\"emailAddress\": \"aasanaliev@critical-factor.com\",\n" + "\"id\": 10,\n"
                    + "\"displayName\": \"Askhat Asanaliev\",\n" + "\"active\": false,\n"
                    + "\"slug\": \"aasanaliev\",\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/users/aasanaliev\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/users/aasanaliev\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "\"role\": \"REVIEWER\",\n" + "\"approved\": true\n" + "}\n"
                    + "],\n" + "\"participants\": [ ],\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/pull-requests/67\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"links\": {\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/pull-requests/67\"\n"
                    + "}\n" + "]\n" + "}\n" + "}\n" + "],\n" + "\"start\": 0,\n" + "\"nextPageStart\": 1\n" + "}";

    public static final String STASH_PULL_REQUEST_JSON =
            "{\n" + "\"id\": 1,\n" + "\"version\": 1,\n" + "\"title\": \"HUB-31\",\n"
                    + "\"description\": \"* Git testing\\ \\ * Deleted test contoller\",\n" + "\"state\": \"MERGED\",\n"
                    + "\"open\": false,\n" + "\"closed\": true,\n" + "\"createdDate\": 1410507192695,\n"
                    + "\"updatedDate\": 1410507333928,\n" + "\"fromRef\": {\n" + "\"id\": \"refs/heads/HUB-31\",\n"
                    + "\"displayId\": \"HUB-31\",\n"
                    + "\"latestChangeset\": \"33537628e7d9bda85897d7861ccc4a56a8b37aa2\",\n" + "\"repository\": {\n"
                    + "\"slug\": \"hub\",\n" + "\"id\": 3,\n" + "\"name\": \"hub\",\n" + "\"scmId\": \"git\",\n"
                    + "\"state\": \"AVAILABLE\",\n" + "\"statusMessage\": \"Available\",\n" + "\"forkable\": true,\n"
                    + "\"project\": {\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "\"public\": false,\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/browse\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"cloneUrl\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"links\": {\n" + "\"clone\": [\n" + "{\n"
                    + "\"href\": \"ssh://git@test-stash.critical-factor.com:7999/ssh/hub.git\",\n"
                    + "\"name\": \"ssh\"\n" + "},\n" + "{\n"
                    + "\"href\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"name\": \"http\"\n" + "}\n" + "],\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/browse\"\n" + "}\n"
                    + "]\n" + "}\n" + "}\n" + "},\n" + "\"toRef\": {\n" + "\"id\": \"refs/heads/master\",\n"
                    + "\"displayId\": \"master\",\n"
                    + "\"latestChangeset\": \"b796f7bf69a2ac66a339dba73f9a19d3b586cd53\",\n" + "\"repository\": {\n"
                    + "\"slug\": \"hub\",\n" + "\"id\": 3,\n" + "\"name\": \"hub\",\n" + "\"scmId\": \"git\",\n"
                    + "\"state\": \"AVAILABLE\",\n" + "\"statusMessage\": \"Available\",\n" + "\"forkable\": true,\n"
                    + "\"project\": {\n" + "\"key\": \"SSH\",\n" + "\"id\": 21,\n"
                    + "\"name\": \"Subutai Social Hub\",\n"
                    + "\"description\": \"The Subutai Social Hub enables sharing configurations and a marketplace so "
                    + "people can share resources, blueprints, templates and plugins for the Subutai platform.\",\n"
                    + "\"public\": false,\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "\"public\": false,\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/browse\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"cloneUrl\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"links\": {\n" + "\"clone\": [\n" + "{\n"
                    + "\"href\": \"ssh://git@test-stash.critical-factor.com:7999/ssh/hub.git\",\n"
                    + "\"name\": \"ssh\"\n" + "},\n" + "{\n"
                    + "\"href\": \"http://daliev@test-stash.critical-factor.com/scm/ssh/hub.git\",\n"
                    + "\"name\": \"http\"\n" + "}\n" + "],\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/browse\"\n" + "}\n"
                    + "]\n" + "}\n" + "}\n" + "},\n" + "\"author\": {\n" + "\"user\": {\n"
                    + "\"name\": \"aasanaliev\",\n" + "\"emailAddress\": \"aasanaliev@critical-factor.com\",\n"
                    + "\"id\": 10,\n" + "\"displayName\": \"Askhat Asanaliev\",\n" + "\"active\": false,\n"
                    + "\"slug\": \"aasanaliev\",\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/users/aasanaliev\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/users/aasanaliev\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "\"role\": \"AUTHOR\",\n" + "\"approved\": false\n" + "},\n"
                    + "\"reviewers\": [\n" + "{\n" + "\"user\": {\n" + "\"name\": \"sakhmataliev\",\n"
                    + "\"emailAddress\": \"sakhmataliev@critical-factor.com\",\n" + "\"id\": 54,\n"
                    + "\"displayName\": \"Sydyk Akhmataliev\",\n" + "\"active\": true,\n"
                    + "\"slug\": \"sakhmataliev\",\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/users/sakhmataliev\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/users/sakhmataliev\"\n" + "}\n" + "]\n" + "}\n"
                    + "},\n" + "\"role\": \"REVIEWER\",\n" + "\"approved\": false\n" + "}\n" + "],\n"
                    + "\"participants\": [ ],\n" + "\"link\": {\n"
                    + "\"url\": \"/projects/SSH/repos/hub/pull-requests/1\",\n" + "\"rel\": \"self\"\n" + "},\n"
                    + "\"links\": {\n" + "\"self\": [\n" + "{\n"
                    + "\"href\": \"http://test-stash.critical-factor.com/projects/SSH/repos/hub/pull-requests/1\"\n"
                    + "}\n" + "]\n" + "}\n" + "}";

    public static final String STASH_PULL_REQUEST_ACTIVITY_JSON =
            "{\n" + "\"size\": 1,\n" + "\"limit\": 1,\n" + "\"isLastPage\": false,\n" + "\"values\": [\n" + "{\n"
                    + "\"id\": 28,\n" + "\"createdDate\": 1410507333928,\n" + "\"user\": {\n"
                    + "\"name\": \"aasanaliev\",\n" + "\"emailAddress\": \"aasanaliev@critical-factor.com\",\n"
                    + "\"id\": 10,\n" + "\"displayName\": \"Askhat Asanaliev\",\n" + "\"active\": false,\n"
                    + "\"slug\": \"aasanaliev\",\n" + "\"type\": \"NORMAL\",\n" + "\"link\": {\n"
                    + "\"url\": \"/users/aasanaliev\",\n" + "\"rel\": \"self\"\n" + "},\n" + "\"links\": {\n"
                    + "\"self\": [\n" + "{\n" + "\"href\": \"http://test-stash.critical-factor.com/users/aasanaliev\"\n"
                    + "}\n" + "]\n" + "}\n" + "},\n" + "\"action\": \"MERGED\",\n" + "\"changeset\": {\n"
                    + "\"id\": \"49c329b78a3e59858c6f2b2ab2cc3ced1ded8a87\",\n" + "\"displayId\": \"49c329b\",\n"
                    + "\"author\": {\n" + "\"name\": \"Askhat Asanaliev\",\n"
                    + "\"emailAddress\": \"aasanaliev@critical-factor.com\"\n" + "},\n"
                    + "\"authorTimestamp\": 1410507334000,\n"
                    + "\"message\": \"Merge pull request #1 in SSH/hub from HUB-31 to master\\ \\ * commit "
                    + "'33537628e7d9bda85897d7861ccc4a56a8b37aa2':\\ Deleted test contoller\\ Git testing\",\n"
                    + "\"parents\": [\n" + "{\n" + "\"id\": \"b796f7bf69a2ac66a339dba73f9a19d3b586cd53\",\n"
                    + "\"displayId\": \"b796f7b\",\n" + "\"author\": {\n" + "\"name\": \"Ernest Kuttubaev\",\n"
                    + "\"emailAddress\": \"ekuttubaev@critical-factor.com\"\n" + "},\n"
                    + "\"authorTimestamp\": 1410421174000,\n" + "\"message\": \"Fix merges\",\n" + "\"parents\": [\n"
                    + "{\n" + "\"id\": \"cf88eb08832abae35f0afaba326dffc0f73c1625\",\n" + "\"displayId\": \"cf88eb0\"\n"
                    + "}\n" + "]\n" + "},\n" + "{\n" + "\"id\": \"33537628e7d9bda85897d7861ccc4a56a8b37aa2\",\n"
                    + "\"displayId\": \"3353762\",\n" + "\"author\": {\n" + "\"name\": \"Askat Asanaliev\",\n"
                    + "\"emailAddress\": \"aasanaliev@safehaus.org\"\n" + "},\n"
                    + "\"authorTimestamp\": 1410507145000,\n" + "\"message\": \"Deleted test contoller\",\n"
                    + "\"parents\": [\n" + "{\n" + "\"id\": \"683ade1713133226a66180592bb87183b618abab\",\n"
                    + "\"displayId\": \"683ade1\"\n" + "}\n" + "]\n" + "}\n" + "],\n" + "\"attributes\": {\n"
                    + "\"jira-key\": [\n" + "\"HUB-31\"\n" + "]\n" + "}\n" + "}\n" + "}\n" + "],\n" + "\"start\": 0,\n"
                    + "\"nextPageStart\": 1\n" + "}";

    public static final String STASH_PULL_REQUEST_COMMITS_JSON =
            "{\n" + "\"values\": [\n" + "{\n" + "\"id\": \"33537628e7d9bda85897d7861ccc4a56a8b37aa2\",\n"
                    + "\"displayId\": \"3353762\",\n" + "\"author\": {\n" + "\"name\": \"Askat Asanaliev\",\n"
                    + "\"emailAddress\": \"aasanaliev@safehaus.org\"\n" + "},\n"
                    + "\"authorTimestamp\": 1410507145000,\n" + "\"message\": \"Deleted test contoller\",\n"
                    + "\"parents\": [\n" + "{\n" + "\"id\": \"683ade1713133226a66180592bb87183b618abab\",\n"
                    + "\"displayId\": \"683ade1\"\n" + "}\n" + "]\n" + "},\n" + "{\n"
                    + "\"id\": \"683ade1713133226a66180592bb87183b618abab\",\n" + "\"displayId\": \"683ade1\",\n"
                    + "\"author\": {\n" + "\"name\": \"Askat Asanaliev\",\n"
                    + "\"emailAddress\": \"aasanaliev@safehaus.org\"\n" + "},\n"
                    + "\"authorTimestamp\": 1410506983000,\n" + "\"message\": \"Git testing\",\n" + "\"parents\": [\n"
                    + "{\n" + "\"id\": \"b796f7bf69a2ac66a339dba73f9a19d3b586cd53\",\n" + "\"displayId\": \"b796f7b\"\n"
                    + "}\n" + "]\n" + "}\n" + "],\n" + "\"size\": 2,\n" + "\"isLastPage\": true,\n" + "\"start\": 0,\n"
                    + "\"limit\": 10,\n" + "\"nextPageStart\": null\n" + "}";

    public static final String STASH_BRANCHES_JSON =
            "{\n" + "    \"size\": 1,\n" + "    \"limit\": 25,\n" + "    \"isLastPage\": true,\n"
                    + "    \"values\": [\n" + "        {\n" + "            \"id\": \"refs/heads/master\",\n"
                    + "            \"displayId\": \"master\",\n"
                    + "            \"latestChangeset\": \"8d51122def5632836d1cb1026e879069e10a1e13\",\n"
                    + "            \"latestCommit\": \"8d51122def5632836d1cb1026e879069e10a1e13\",\n"
                    + "            \"isDefault\": true\n" + "        }\n" + "    ],\n" + "    \"start\": 0\n" + "}";

    public static  final String STASH_BRANCH_JSON ="{\n" + "    \"id\": \"refs/heads/master\",\n"
            + "    \"displayId\": \"master\",\n"
            + "    \"latestChangeset\": \"8d51122def5632836d1cb1026e879069e10a1e13\",\n"
            + "    \"latestCommit\": \"8d51122def5632836d1cb1026e879069e10a1e13\",\n" + "    \"isDefault\": true\n"
            + "}";
}
